name: releaser
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
      - name: Get fyne-cross
        run: go install github.com/fyne-io/fyne-cross@v1.6.1
      - name: Build android app
        env:
          tag: ${{ github.ref_name }}
        run: fyne-cross android -image fyneio/fyne-cross-images:v1.2.0-android -app-version "${tag#v}"
      - name: Release pushed tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${tag#v}" --generate-notes ./fyne-cross/dist/android/*.apk