name: releaser
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'
      - name: Get fyne-cross
        run: go install github.com/fyne-io/fyne-cross@latest
      - name: Build android app
        run: fyne-cross android
      - uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "./fyne-cross/dist/android/*"